62731 - INVOICE : Unable to register a payment - better fix
axelor/axelor-open-suite pull request #10130
Opened 2023-04-04 14:15 UTC by alg-axelor

2023-04-04 14:19 UTC, gdu-axelor requested changes

2023-04-04 14:19 UTC, gdu-axelor commented on axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderMoveServiceImpl.java
> +          generateMoves(bankOrderLine);
I think a JPA.find() is missing here.

2023-04-04 14:19 UTC, gdu-axelor commented on axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderMoveServiceImpl.java
> +      int fetchSize = 20;
Better to use a static param for define the fetchSize

2023-04-05 09:56 UTC, jmi-axelor approved these changes

2023-04-17 14:06 UTC, merged