RM#58442: INVOICE / INVOICE PAYMENT / INVOICE TERM: corrected financial discount not updatable on invoice-term, on invoice payment and early on invoice.
axelor/axelor-open-suite pull request #10200
Opened 2023-04-17 13:31 UTC by jdo-axelor

2023-04-17 20:26 UTC, jmi-axelor requested changes

2023-04-17 20:26 UTC, jmi-axelor commented on axelor-account/src/main/resources/views/InvoicePayment.xml
> +          onChange="action-invoice-payment-method-update-discount"/>
I tried to pay a customer Invoice with an InvoicePayment. The invoice had a 10% financialDiscount, the total before discount was 84€.
So when I tried to pay it with an InvoicePayment, the default computed amount for the InvoicePayment was 75.6€ (84€ - 10%), there was a financialDiscount on the InvoicePayment, I removed it and tried to pay the whole Invoice, so 84€ and I get the following error message:
"Le montant payé est supérieur au(x) montant(s) restant à payer sur le(s) échéance(s)."
For me, if we decide to remove the financialDiscount on the InvoicePayment, we should be able to pay the whole Invoice without the discount. 

Also when we delete the financialDiscount, set applyFinancialDiscount to false. And put applyFinancialDiscount outside of the discountPanel and remove the `readonly="true"`

2023-04-17 20:26 UTC, jmi-axelor commented on axelor-account/src/main/resources/views/InvoiceTerm.xml
> +          onChange="action-invoice-term-method-update-financial-discount"/>
when you delete the financialDiscount, set applyFinancialDiscount  to false

2023-05-22 12:36 UTC, jdo-axelor commented on axelor-account/src/main/resources/views/InvoicePayment.xml
>          <field name="financialDiscountDeadlineDate"/>
Specification ticket, "Also, when I register a payment (InvoicePayment), I should be able to remove or change the selected financial discount", the readonly if if is on the panel

2023-07-25 13:33 UTC, closed without merging