#63365: ProjectPlanningTime : Manage project units and improve UX
axelor/axelor-open-suite pull request #10313
Opened 2023-05-03 16:39 UTC by cce-axelor

2023-05-23 15:20 UTC, ale-axelor requested changes

2023-05-23 15:20 UTC, ale-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetServiceImpl.java
> +    timesheetLine.setDate(projectPlanningTime.getStartDateTime().toLocalDate());
can you check if `startDateTime` can be null here ? With the previous code it did not cause any issue if the field was null, but now the call to `.toLocalDate()` will throw a NPE

2023-05-24 11:04 UTC, cce-axelor commented on axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/app/AppBusinessProjectServiceImpl.java
> +          I18n.get(BusinessProjectExceptionMessage.PROJECT_CONFIG_DEFAULT_HOURS_PER_DAY_MISSING));
PROJECT_CONFIG_DEFAULT_HOURS_PER_DAY_MISSING message is not adapted

2023-05-24 11:04 UTC, cce-axelor commented on axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/app/AppBusinessProjectServiceImpl.java
> +          I18n.get(BusinessProjectExceptionMessage.PROJECT_CONFIG_DEFAULT_HOURS_PER_DAY_MISSING));
Same here

2023-05-24 11:04 UTC, cce-axelor commented on axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/app/AppBusinessProjectServiceImpl.java
> +    return getAppBusinessProject().getHoursUnit();
Store getAppBusinessProject().getDaysUnit() and getAppBusinessProject().getHoursUnit() in a variable

2023-05-30 10:12 UTC, merged