Feature RM#65938 [LEAVES/LUNCH VOUCHER] New Sage export
axelor/axelor-open-suite pull request #10805
Opened 2023-07-05 14:52 UTC by jka-axelor

2023-08-21 12:03 UTC, alo-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/leave/LeaveServiceImpl.java
> +      printer.printRecord(header);
This can be separated in another method createHeader.

2023-08-21 12:05 UTC, alo-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/leave/LeaveServiceImpl.java
> +        printer.printRecord(line);
This can be separated in another method addCsvLine

2023-08-21 12:14 UTC, alo-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/lunch/voucher/LunchVoucherMgtServiceImpl.java
> +    return metaFile;
This method is duplicated in LeaveServiceImpl, you could create a new service in axelor-base MetafileUploadService.

2023-08-21 12:15 UTC, alo-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/leave/LeaveService.java
> +  public MetaFile export(List<Long> ids, User user) throws IOException, AxelorException;
Please create a new service LeaveExportService and move this method there.

2023-08-21 12:16 UTC, alo-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/lunch/voucher/LunchVoucherMgtServiceImpl.java
>    public void export(LunchVoucherMgt lunchVoucherMgt) throws IOException {
Please create a new service LunchVoucherExportService and move this method there.

2023-08-21 12:16 UTC, alo-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/lunch/voucher/LunchVoucherMgtServiceImpl.java
> +      printer.printRecord(header);
This can be separated in another method createHeader.

2023-08-21 12:17 UTC, alo-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/lunch/voucher/LunchVoucherMgtServiceImpl.java
> +        printer.printRecord(line);
This can be separated in another method addCsvLine.

2023-08-21 12:17 UTC, alo-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/service/lunch/voucher/LunchVoucherMgtServiceImpl.java
> +                + ".csv",
This could be separated in another method computeExportFileName

2023-09-05 09:11 UTC, ale-axelor requested changes

2023-09-05 09:11 UTC, ale-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/web/leave/LeaveController.java
> +                .fetch().stream()
Please, instead of using a stream to get the id, modify the query to `SELECT` and retrieve directly only the ids, to improve performances.

2023-09-08 15:01 UTC, merged