65622 feat: [Sonar] Potential NPE InvoiceTermServiceImpl
axelor/axelor-open-suite pull request #10965
Opened 2023-07-29 16:56 UTC by pud-axelor

2023-08-01 08:48 UTC, cce-axelor requested changes

2023-08-01 08:48 UTC, cce-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceTermServiceImpl.java
> +    if (move != null && invoiceTerm != null && invoiceTerm.getOriginDate() == null) {
I think you need to keep the test on moveLine because it's a functional test more than a technical one.

2023-08-01 08:51 UTC, pud-axelor commented
Alright understood

On Tue, Aug 1, 2023, 9:49 AM cce-axelor ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceTermServiceImpl.java
> <https://github.com/axelor/axelor-open-suite/pull/10965#discussion_r1280304665>
> :
>
> > -    if (moveLine != null && invoiceTerm.getOriginDate() == null) {
> +    if (move != null && invoiceTerm != null && invoiceTerm.getOriginDate() == null) {
>
> I think you need to keep the test on moveLine because it's a functional
> test more than a technical one.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/axelor/axelor-open-suite/pull/10965#pullrequestreview-1556476307>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBM2HW6KPA4X6VOQBYQ2VD3XTC7IJANCNFSM6AAAAAA24TNC4I>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-01 13:32 UTC, pud-axelor commented
@cce-axelor this has been resolved

2023-08-24 11:55 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceTermServiceImpl.java
> +    if (move != null && moveLine != null && invoiceTerm != null && invoiceTerm.getOriginDate() == null) {
I don't think it makes sense to check if invoiceTerm is null here, you can just check it at the start of the method and add a `return;` in that case

2023-08-24 11:55 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceTermServiceImpl.java
> +        if (move != null)
Please use a `else if` here

2023-08-25 07:45 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceTermServiceImpl.java
> +    if (invoiceTerm == null) return;
Please respect coding conventions and add a `{ }` block for return

2023-10-26 12:42 UTC, closed without merging