69555 fix anomaly on draft global budget budget level deletion
axelor/axelor-open-suite pull request #11280
Opened 2023-10-04 08:26 UTC by jma-axelor

2023-10-05 12:47 UTC, rth-axelor commented on axelor-budget/src/main/resources/i18n/messages_fr.csv
> +"Warning, you will delete all versions linked to this budget, do you want to continue ?","Attention, vous allez supprimer toutesl es versions liées à ce budget, voulez-vous contibuer ?",,
Typing error
Attention, vous allez supprimer toutes les versions liées à ce budget, voulez-vous continuer ?

2023-10-11 08:01 UTC, rth-axelor commented on axelor-budget/src/main/java/com/axelor/apps/budget/web/GlobalBudgetController.java
>      response.setValues(globalBudget);
Just remove the set values because it's not used with the reload

2023-10-11 11:33 UTC, ale-axelor requested changes

2023-10-11 11:33 UTC, ale-axelor commented on axelor-budget/src/main/resources/views/GlobalBudget.xml
> +          colSpan="12" onClick="action-global-budget-group-draft-children, save"/>
if you use `setReload(true)` in the Controller, the `save` should be before the call to the method, and not after, so please change it.

2023-10-12 08:06 UTC, merged