69346 - Fix NPE when we reconcile move lines
axelor/axelor-open-suite pull request #11358
Opened 2023-10-12 13:13 UTC by paa-axelor

2023-10-16 21:03 UTC, jmi-axelor requested changes

2023-10-26 13:45 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineTaxServiceImpl.java
> +          && moveLine.getTaxLine() == null) {
I think that part of the condition can be factorized with the one used in `MoveLineAttrsServiceImpl.addTaxLineRequired`

2023-10-26 13:45 UTC, aol-axelor commented on axelor-account/src/main/resources/views/MoveLine.xml
> +          readonlyIf="account.accountType.technicalTypeSelect == 'income' || account.accountType.technicalTypeSelect == 'charge' || account.accountType.technicalTypeSelect == 'tax' || account.account
Please use an array here to check technicalTypeSelect

2023-10-26 13:45 UTC, aol-axelor commented on axelor-account/src/main/resources/views/MoveLine.xml
> +          readonlyIf="account.accountType.technicalTypeSelect != 'tax' || (move.statusSelect != 1 &amp;&amp; move.statusSelect != 5)"/>
Please use an array here to check statusSelect

2023-10-26 13:45 UTC, aol-axelor commented on axelor-account/src/main/resources/views/MoveLine.xml
> +          readonlyIf="(move.statusSelect != 1 &amp;&amp; move.statusSelect != 5) || account.accountType.technicalTypeSelect != 'tax'"
Same as before

2023-11-09 13:29 UTC, merged