Feature RM#71348:[STOCKMOVE] M2M instead of M2O towards sale order an…
axelor/axelor-open-suite pull request #11490
Opened 2023-11-03 13:37 UTC by bsu-axelor

…d purchase order

2023-11-30 09:30 UTC, kra-axelor requested changes

2023-11-30 09:30 UTC, kra-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveServiceSupplychainImpl.java
> +          Beans.get(SaleOrderStockService.class).updateDeliveryState(saleOrder);
Hello, please replace Beans.get by injection by constructor, especially now since we are in a for each

2023-11-30 09:30 UTC, kra-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveServiceSupplychainImpl.java
> +          Beans.get(PurchaseOrderStockService.class).updateReceiptState(purchaseOrder);
please replace Beans.get by injection by constructor

2023-11-30 09:30 UTC, kra-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveServiceSupplychainImpl.java
> +      Beans.get(SaleOrderStockService.class).updateDeliveryState(so);
please replace Beans.get by injection by constructor

2023-11-30 09:30 UTC, kra-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveServiceSupplychainImpl.java
> +      Beans.get(PurchaseOrderStockService.class).updateReceiptState(po);
please replace Beans.get by injection by constructor

2023-12-11 13:27 UTC, ale-axelor requested changes

2023-12-12 12:45 UTC, merged