RM#71767 : Add preview to doubtful customer batch
axelor/axelor-open-suite pull request #11590
Opened 2023-11-15 14:21 UTC by aol-axelor

2024-01-02 19:50 UTC, jmi-axelor requested changes
Update the translations files

2024-01-02 19:50 UTC, jmi-axelor commented on axelor-account/src/main/resources/views/MoveLine.xml
> +    <field name="taxLine"/>
remove the taxLine column, it's always empty on customer account MoveLines

2024-01-08 15:36 UTC, jmi-axelor approved these changes

2024-01-10 13:14 UTC, ale-axelor requested changes

2024-01-10 14:04 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceTermReplaceServiceImpl.java
> +  }
Somehow that part was not working anymore with this change

2024-01-10 14:42 UTC, merged