RM#71613: TRANSLATIONS : Export/import translations
axelor/axelor-open-suite pull request #11747
Opened 2023-12-07 21:28 UTC by tyu-axelor

2023-12-08 17:25 UTC, jmi-axelor approved these changes

2023-12-08 17:31 UTC, jmi-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/web/ImportExportTranslationController.java
> +      response.setInfo("The import file is empty or it has error format.");
This message can't be translated, please check other controllers to see how to make it translatable

2023-12-08 17:32 UTC, jmi-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/web/ImportExportTranslationController.java
> +      response.setInfo("File successfully imported.");
This message can't be translated, please check other controllers to see how to make it translatable

2023-12-12 14:32 UTC, jmi-axelor requested changes

2023-12-12 14:32 UTC, jmi-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/service/ImportExportTranslationServiceImpl.java
> +                    + ") ")
add an order by mt.id just to be sure

2023-12-12 22:07 UTC, jmi-axelor requested changes

2023-12-12 22:07 UTC, jmi-axelor commented on changelogs/unreleased/71613.yml
> +  Other available languages can be exported into a csv file, and can be modified by user after downloading.
Change these lines, native languages don't exist anymore

2023-12-12 22:07 UTC, jmi-axelor commented on axelor-base/src/main/resources/apps/demo-data/fr/base_language.csv
> +2;"Français";"fr"
try to remove this modification, nothing should change in this file

2023-12-12 22:07 UTC, jmi-axelor commented on axelor-base/src/main/resources/data-init/input/base_language.csv
> +2;"French";"fr"
try to remove this modification, nothing should change in this file

2023-12-13 15:27 UTC, ale-axelor requested changes

2023-12-14 09:13 UTC, merged