RM#72270: BANKDETAILS : use a template for internationalization
axelor/axelor-open-suite pull request #11863
Opened 2024-01-10 15:34 UTC by tyu-axelor

2024-02-08 20:41 UTC, jmi-axelor commented on axelor-base/src/main/resources/views/BankDetails.xml
> +    onLoad="action-group-account-bank-details-form-onload, action-bank-details-attrs-fields-to-be-shown"
create an action-group please

2024-02-08 20:42 UTC, jmi-axelor commented on axelor-base/src/main/resources/views/BankDetails.xml
> +        == 'Account Number'}?.size() &gt; 0" -->
remove this comment

2024-02-08 20:44 UTC, jmi-axelor commented on axelor-base/src/main/resources/views/BankDetailsTemplate.xml
> +  <form name="bank-details-template-form" title="Bank details templates"
Title should be "Bank details template"

2024-02-08 20:44 UTC, jmi-axelor commented on axelor-base/src/main/resources/views/BankDetailsTemplateLine.xml
> +  <form name="bank-details-template-line-form" title="Bank details template lines"
Title should be "Bank details template line"

2024-02-08 20:46 UTC, jmi-axelor commented on axelor-base/src/main/resources/views/BankDetailsTemplate.xml
> +    <field name="bankDetailsTemplateLineList" title="Fields to use"/>
don't put this list in the grid

2024-02-14 21:22 UTC, jmi-axelor requested changes

2024-02-14 21:22 UTC, jmi-axelor commented on axelor-base/src/main/resources/apps/demo-data/base-config.xml
why did you change this file?

2024-02-14 21:26 UTC, tyu-axelor commented on axelor-base/src/main/resources/apps/demo-data/base-config.xml
There is a economicArea on a country object. If the economicArea demo data is imported after country, then the field is empty on country.

2025-02-03 16:35 UTC, closed without merging