RM#75439 BILLOFMATERIALIMPORT documents management
axelor/axelor-open-suite pull request #12188
Opened 2024-02-29 13:10 UTC by dar-axelor

2024-03-01 10:08 UTC, cce-axelor commented on changelogs/unreleased/75439.yml
axelor-base or axelor-production ?

2024-03-11 15:55 UTC, ale-axelor requested changes

2024-03-11 15:55 UTC, ale-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/service/DMSServiceImpl.java
> +      ZipInputStream zis = new ZipInputStream(new FileInputStream(zipFilePath));
please use try-with-resource statement, currently if we get an exception, the stream will never be closed.

2024-03-11 15:55 UTC, ale-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/service/DMSServiceImpl.java
> -  @Override
please keep this `@Override`

2024-03-12 17:20 UTC, merged