RM-82810 Create a product price API
axelor/axelor-open-suite pull request #13049
Opened 2024-08-06 16:19 UTC by mea-axelor

2024-08-08 12:13 UTC, alo-axelor commented on axelor-sale/src/main/java/com/axelor/apps/sale/rest/dto/CurrencyResponse.java
> +  }
There should be only one constructor with Currency as parameter, we can create a method in a service to create the CurrencyResponse. This way we can null check currency in company and product.

2024-08-08 12:13 UTC, alo-axelor commented on axelor-sale/src/main/java/com/axelor/apps/sale/service/ProductRestServiceImpl.java
> +            I18n.get(SaleExceptionMessage.PRODUCT_IS_NULL));
Please add translation for exception messages.

2024-08-08 12:13 UTC, alo-axelor commented on axelor-sale/src/main/java/com/axelor/apps/sale/rest/ProductRestController.java
> +        Beans.get(ProductRestService.class).fetchProductPrice(product, partner, company);
This code can be move in a method computing and returning the ProductResponse.

2024-08-12 15:49 UTC, alo-axelor commented on axelor-sale/src/main/java/com/axelor/apps/sale/service/ProductRestServiceImpl.java
> +        Beans.get(ProductRestService.class).fetchProductPrice(product, partner, company);
Remove Beans.get

2024-08-14 08:59 UTC, alo-axelor commented on axelor-sale/src/main/java/com/axelor/apps/sale/service/ProductRestServiceImpl.java
> +            .setScale(nbrDecimalDigit, RoundingMode.HALF_DOWN);
in AOS, we don't use RoundingMode.HALF_DOWN, use RoundingMode.HALF_UP instead.

2024-08-14 08:59 UTC, alo-axelor commented on axelor-sale/src/main/java/com/axelor/apps/sale/service/ProductRestServiceImpl.java
> +          .getAmountCurrencyConvertedAtDate(productCurrency, companyCurrency, price, localDate);
In AOS, we always use brackets for a if-block, even if there is only one line. Please add the brackets.
Also remove Beans.get.

2024-08-27 09:05 UTC, ale-axelor requested changes

2024-08-27 09:05 UTC, ale-axelor commented on axelor-sale/src/main/java/com/axelor/apps/sale/service/ProductRestServiceImpl.java
> +  public List<PriceResponse> fetchProductPrice(Product product, Partner partner, Company company)
this should not be a public method, please change it to protected

2024-08-27 09:05 UTC, ale-axelor commented on axelor-sale/src/main/java/com/axelor/apps/sale/service/ProductRestServiceImpl.java
> +  }
I don't think the product can be null here. if we send an id which does not exist, we should get an exception when finding the product in the rest controller. If we do not send an id, we should get an exception from RequestValidator.

2024-08-27 09:05 UTC, ale-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/service/ProductPriceService.java
> +  BigDecimal getSaleUnitPrice(Company company, Product product, Boolean inAti, Partner partner)
please use a `boolean` instead of a boxed `Boolean` which is nullable.

2024-08-28 09:26 UTC, merged