Modify appBaseService.getTodayDate()
axelor/axelor-open-suite pull request #5902
Opened 2020-09-28 16:34 UTC by lde-axelor

Modify appBaseService.getTodayDate() method to take into account the given company's timezone.

2020-10-01 14:28 UTC, ale-axelor requested changes

2020-10-01 14:28 UTC, ale-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/service/app/AppBaseServiceImpl.java
> +import com.axelor.apps.base.db.*;
please do not use wildcards for import

2020-10-01 14:28 UTC, ale-axelor commented on axelor-contract/src/main/java/com/axelor/apps/contract/service/ConsumptionLineServiceImpl.java
> +            line.getContractLine().getContractVersion().getContract().getCompany()));
it would be safer to check for NPE (I think using optional.map will be useful here)

2020-10-02 07:57 UTC, lde-axelor commented on axelor-account/src/main/java/com/axelor/csv/script/ImportMoveTemplate.java
> +        String dateShift = values.get("endOfValidityDateShift").toString();
No, an empty value in a csv always lead to an empty String in my tests.

2020-10-02 08:33 UTC, merged