RM#38230 : Add possibility to select lines for mrp generation
axelor/axelor-open-suite pull request #6615
Opened 2021-05-25 08:18 UTC by aol-axelor

2021-05-25 09:47 UTC, ale-axelor requested changes

2021-05-25 09:47 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/MrpLineController.java
> +      }
Add a new method in a service to update mrpLine in database

2021-05-25 09:47 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/MrpLineController.java
> +  private void toggle(ActionRequest request, ActionResponse response, boolean value) {
please do not call a variable "value", here call it `proposalToProcess` instead

2021-05-25 09:47 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/MrpLineController.java
> +      Query<MrpLine> mrpLineQuery =
Create a new separate method in a service

2021-05-25 09:47 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/MrpLineController.java
> +                      + " OR (self.mrp.displayProductWithoutProposal = false AND self.mrp.id = ?1 AND self.product.id IN (select m.product from MrpLine as m where m.mrp.id = ?1 AND m.mrpLineType.elem
this line is too wide, please split it to follow our style convention.
Also please use named parameters to improve maintainability and readability.

2021-05-25 09:47 UTC, ale-axelor commented on axelor-supplychain/src/main/resources/domains/MrpLine.xml
> +  		<boolean name="toProcess" title="To process" default="false"/>
Please rename `toProcess` to `proposalToProcess` (the title can stay the same), to avoid confusion.

2021-05-25 09:47 UTC, ale-axelor commented on changelogs/unreleased/feature-select-lines-for-mrp-generation.yml
> +title: "Supplychain : Add possibility to select lines for mrp generation"
```suggestion
title: "Mrp: add possibility to select lines for proposal generation"
```

2021-05-25 22:20 UTC, gdu-axelor requested changes

2021-05-25 22:20 UTC, gdu-axelor commented on axelor-supplychain/src/main/resources/views/MrpLine.xml
> +       <button name="selectOneBtn" icon="fa-check" onClick="action-mrp-line-record-select" readonlyIf="proposalToProcess"/>
action-record without save ?

2021-06-15 13:15 UTC, ale-axelor requested changes

2021-06-15 13:15 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/MrpLineController.java
> +      }
This block of code should be in a new method, in mrpLineService

2021-06-15 13:15 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/MrpLineController.java
> +    response.setAttr("mrpLinePanel", "refresh", true);
Everything in this method must be called inside a `try {...} catch` block

2021-06-15 13:15 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/MrpLineController.java
> +    response.setAttr("mrpLinePanel", "refresh", true);
Everything in this method must be called inside a `try {...} catch` block

2021-06-17 08:58 UTC, merged