Feature RM#44063 INVOICE / INVOICETERM / PASSFORPAYMENT : Adapt invoi…
axelor/axelor-open-suite pull request #7328
Opened 2021-12-17 11:09 UTC by pda-axelor

…ce PFP Features to fit with the implementation of PFP on invoiceTerm (PROCESS)

2021-12-28 13:27 UTC, gdu-axelor requested changes

2021-12-28 13:27 UTC, gdu-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceServiceImpl.java
> +        Beans.get(AppBaseService.class).getTodayDate(invoice.getCompany()));
AppBaseService is already injected in the class constructor

2022-01-04 08:58 UTC, ssb-axelor requested changes

2022-01-04 08:58 UTC, ssb-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceServiceImpl.java
>          Beans.get(AppBaseService.class).getTodayDate(invoice.getCompany()));
Please call injected service appBaseService here as well. Thanks

2022-01-10 14:54 UTC, merged