45302 move simplified
axelor/axelor-open-suite pull request #7446
Opened 2022-01-18 14:48 UTC by rth-axelor

2022-02-03 10:58 UTC, aol-axelor commented on axelor-account/src/main/resources/views/MoveLine.xml
> +    <field name="isOtherCurrency" hidden="true"/>
Please put all hidden fields at the end (or remove if unnecessary) and remove their other attributes

2022-02-03 10:58 UTC, aol-axelor commented on axelor-account/src/main/resources/views/Move.xml
> +    </panel-tabs>
All panels from panel tab are hidden so remove if unnecessary

2022-02-03 10:58 UTC, aol-axelor commented on axelor-account/src/main/resources/views/Move.xml
> +        <field name="journal.authorizeSimulatedMove" hidden="true"/>
Remove hidden fields if unnecessary

2022-02-03 10:58 UTC, aol-axelor commented on axelor-account/src/main/resources/views/Move.xml
> +            onChange="action-move-record-journal,action-move-method-get-period,action-move-attrs-validate-button-title,action-method-hide-axis-analytic-account-move-line"
Please put actions in action-group

2022-02-03 10:58 UTC, aol-axelor commented on axelor-account/src/main/resources/views/Move.xml
> +          <field name="originDate" hidden="true" colSpan="3"/>
Please remove hidden fields if unnecessary

2022-02-03 10:58 UTC, aol-axelor commented on axelor-account/src/main/resources/views/Move.xml
> +            onChange="action-move-record-set-currency-code"/>
Please remove hidden fields if unnecessary

2022-02-03 10:58 UTC, aol-axelor commented on axelor-account/src/main/resources/views/Move.xml
> +          <field name="$journalTechnicalTypeSelect" hidden="true" type="integer"/>
Please remove hidden field if unnecessary

2022-02-07 14:58 UTC, ale-axelor requested changes

2022-02-09 14:08 UTC, merged