46684
axelor/axelor-open-suite pull request #7619
Opened 2022-02-24 15:23 UTC by rth-axelor

2022-03-17 14:55 UTC, ale-axelor requested changes

2022-03-17 14:55 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/AccountController.java
> +            ActionView.define("Specific Analytic Distribution Template")
Please translate this title

2022-04-07 17:20 UTC, ale-axelor requested changes

2022-04-07 17:20 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/AccountController.java
> +        System.err.println(specificAnalyticDistributionTemplate);
Please remove this System.err.println

2022-04-14 08:46 UTC, ale-axelor requested changes

2022-04-14 08:46 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/analytic/AnalyticDistributionTemplateServiceImpl.java
> +  @Transactional
Please see our documentation/convention with Transactional annotation

2022-04-14 08:46 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/AccountController.java
> +          && specificAnalyticDistributionTemplate != null) {
Please move this logic to a new method in a service

2022-04-14 08:46 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/FixedAssetController.java
> +            ActionView.define(I18n.get("Specific Analytic Distribution Template"))
Please create a constant in IExceptionMessage

2022-04-21 21:08 UTC, jmi-axelor approved these changes

2022-04-21 21:08 UTC, merged