46873
axelor/axelor-open-suite pull request #7644
Opened 2022-03-03 08:20 UTC by rth-axelor

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineService.java
> +  MoveLine checkAnalyticMoveLineForAxis(MoveLine moveLine);
Same as before, please add in a specific analytic related service (along with other methods if there are)

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineServiceImpl.java
> +
Same comments as for what was done on invoice lines

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/AnalyticDistributionTemplateController.java
> +          .validateTemplatePercentages(analyticDistributionTemplate);
Please keep `response.setError` as catching the exception doesn't prevent further actions in `action-group` to be executed

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +      Invoice invoice = request.getContext().getParent().asType(Invoice.class);
Please check if context has parent to prevent NPE

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +      Invoice invoice = request.getContext().getParent().asType(Invoice.class);
Same as before

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +      for (int i = 1; i <= 5; i++) {
Please add global constants to define min and max

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +        for (int i = 1; i <= 5; i++) {
Same as before

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +                  && (i <= nbrAxis));
Please add condition in a separate method in service

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +          for (int i = 1; i <= 5; i++) {
Same as before

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +            response.setAttr("axis" + i + "AnalyticAccount", "domain", "self.id IN (0)");
Please don't use string concatenation

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/MoveLineController.java
> -
Same comments for what was done on invoice lines

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/resources/views/InvoiceLine.xml
> +          if="__config__.app.isApp('account') &amp;&amp; __config__.app.getApp('account').getManageAnalyticAccounting()"
I don't think `if="__config__.app.isApp('account')` is necessary as we are in `account` module
Same goes for other cases

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/resources/views/InvoiceLine.xml
> +          onChange="action-method-invoice-line-axis-create-analytic-line"/>
Please replace `account.analyticDistributionAuthorized == false` with `!account.analyticDistributionAuthorized`

2022-03-04 15:56 UTC, aol-axelor commented on axelor-account/src/main/resources/views/InvoiceLine.xml
> +  </action-group>
Please respect action naming convention `action-{objet name}-{action type}-{action-description}`
Same goes for new actions in the following

2022-03-04 15:56 UTC, aol-axelor commented on axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/InvoiceLineProjectServiceImpl.java
> +      SupplierCatalogService supplierCatalogService) {
No need to add with analytic themed refactor

2022-03-04 15:56 UTC, aol-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/InvoiceLineSupplychainService.java
> +      SupplierCatalogService supplierCatalogService) {
Same as before

2022-03-17 10:34 UTC, ale-axelor requested changes

2022-03-17 10:34 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +      throws AxelorException {
Please remove throw declaration when the method in fact does not throw the exception

2022-03-17 10:34 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +      throws AxelorException {
Please remove throw declaration when the method in fact does not throw the exception

2022-03-17 10:34 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +                Beans.get(InvoiceLineAnalyticService.class).getAxisDomains(invoiceLine, invoice, i);
Please move the call to `Beans.get` outside the for loop

2022-03-17 10:34 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
> +      throws AxelorException {
Please remove throw declaration when the method in fact does not throw the exception

2022-03-17 10:34 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/MoveLineController.java
> +              Beans.get(MoveLineComputeAnalyticService.class).setAxisDomains(moveLine, move, i);
Please move Beans.get calls outside of the for loop

2022-03-17 10:34 UTC, ale-axelor commented on axelor-account/src/main/resources/i18n/messages_fr.csv
> +"Invalid analytic move lines, some axes percentage values are different than 100%.","Répatition analytique invalide, un ou des axes ont des pourcentages différents de 100%",,
"Répatition" => "Répartition"

2022-03-24 16:51 UTC, closed without merging