commit after fixing filter partner by type
axelor/axelor-open-suite pull request #7683
Opened 2022-03-08 16:30 UTC by ija-axelor

2022-03-09 09:47 UTC, aol-axelor commented on changelogs/unreleased/47145-fix-filter-partner.yml
> +title :"fix filter in partner"
Please add a bit more detail and add the main concerned object
Like `MOVE : Fix partner not being filtered according to payment mode compatible types`

2022-03-11 10:20 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveToolService.java
> +    if (journal != null && journal.getCompatiblePartnerTypeSelect() != null && !journal.getCompatiblePartnerTypeSelect().isEmpty()) {
`journal.getCompatiblePartnerTypeSelect() != null && !journal.getCompatiblePartnerTypeSelect().isEmpty()` can be simplified by `!StringUtils.isEmpty(journal.getCompatiblePartnerTypeSelect())`

2022-03-11 10:20 UTC, aol-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/service/PartnerServiceImpl.java
> +    return (!type.isEmpty() && (type!=null)) ? Query.of(Partner.class).filter("self." + type + "=true").fetch().stream()
Same as before

2022-03-11 10:20 UTC, aol-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/service/PartnerServiceImpl.java
> +        .collect(Collectors.toList()) : null;
I think it would be better to return an empty list

2022-03-11 10:20 UTC, aol-axelor commented on axelor-base/src/main/java/com/axelor/apps/base/service/PartnerServiceImpl.java
> -    return Query.of(Partner.class).filter("self." + type + "=true").fetch().stream()
Please use either `String.format` or `StringBuilder` for string concatenation

2022-03-12 13:39 UTC, aol-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveToolService.java
> +      StringBuilder compatiblePartnerDomain = new StringBuilder("AND self.id IN (");
I think it's better if the `AND` is added outside of this method, so it can be used independently

2022-05-17 18:42 UTC, jmi-axelor approved these changes

2022-05-25 15:11 UTC, ale-axelor requested changes

2022-06-10 09:54 UTC, merged