47376 remove of 1006-1009 accounting report type
axelor/axelor-open-suite pull request #7711
Opened 2022-03-13 21:07 UTC by rth-axelor

2022-03-15 20:37 UTC, gdu-axelor requested changes

2022-03-15 20:37 UTC, gdu-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/MoveLineExportServiceImpl.java
> +    header =
should be removed

2022-03-25 10:54 UTC, ale-axelor requested changes

2022-03-25 10:54 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/MoveLineExportServiceImpl.java
>      String header = "";
Please simplify this line with the line under it

2022-03-25 17:02 UTC, merged