RM#47595 : Fix NPE when creating invoice term from move line
axelor/axelor-open-suite pull request #7765
Opened 2022-03-22 12:22 UTC by aol-axelor

2022-04-07 16:35 UTC, ale-axelor requested changes
Please review the methods, a service method should not use Context objects as they are specific to the views and must only be called in Controller classes.

2022-05-10 21:50 UTC, jmi-axelor commented
Need to apply spotless on your branch

2022-05-10 21:55 UTC, jmi-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceTermController.java
> +          if (request.getContext().getParent().get("_model").toString().contains("MoveLine")) {
Why do you replace the ContexTool.getContextParent?

2022-05-10 21:55 UTC, jmi-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceTermController.java
> -            Move move = ContextTool.getContextParent(request.getContext(), Move.class, 2);
Same here

2022-05-11 18:33 UTC, merged