RM#48112 - firing events instead of overriding BankOrderService
axelor/axelor-open-suite pull request #7856
Opened 2022-04-05 09:15 UTC by oma-axelor

2022-04-05 09:32 UTC, dtr-axelor requested changes

2022-04-06 09:43 UTC, ale-axelor requested changes

2022-04-06 09:43 UTC, ale-axelor commented on axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderServiceImpl.java
>    @Inject
Please use injection by constructor, and move the field to protected

2022-04-06 09:43 UTC, ale-axelor commented on axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderServiceImpl.java
> +        .select(NamedLiteral.of("validatePayment"))
Please define constants String in BankOrderValidated instead of using a hard coded value here.

2022-04-06 09:43 UTC, ale-axelor commented on axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderServiceImpl.java
> +        .select(NamedLiteral.of("cancelPayment"))
see above

2022-04-06 09:43 UTC, ale-axelor commented on axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderServiceImpl.java
> +        .select(NamedLiteral.of("validate"))
see above

2022-04-06 09:43 UTC, ale-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/observer/BankOrderHRObserver.java
> +  void onValidatePayment(@Observes @Named("validatePayment") BankOrderValidated event)
Use the newly defined constant in BankOrderValidated here

2022-04-06 09:43 UTC, ale-axelor commented on axelor-human-resource/src/main/java/com/axelor/apps/hr/observer/BankOrderHRObserver.java
> +  void onCancelPayment(@Observes @Named("cancelPayment") BankOrderValidated event)
Use the newly defined constant in BankOrderValidated here

2022-04-06 09:43 UTC, ale-axelor commented on changelogs/unreleased/48112.yml
> +---
Please remove this changelog entry since this is a refactor with no functional change

2022-04-06 10:27 UTC, dtr-axelor commented
@ale-axelor @oma-axelor I did the requested changes and created a new PR in my fork: https://github.com/axelor/axelor-open-suite/pull/7861.

2022-04-06 13:33 UTC, closed without merging