Feature #48812 : US 34.2 : Revue des fichiers CSV de l'ensemble des m…
axelor/axelor-open-suite pull request #7987
Opened 2022-04-28 13:39 UTC by bsu-axelor

…odules (Standards) de l'application

2022-04-29 18:07 UTC, gdu-axelor requested changes

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-crm/src/main/resources/i18n/messages_fr.csv
> +"Action","Action",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-crm/src/main/resources/i18n/messages_fr.csv
> +"Roles","Rôles",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-crm/src/main/resources/i18n/messages_fr.csv
> +"Urgent","Urgent",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"Completed","Complété",,
terminé ?

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"DATE D'ENTREE",,"Key in FR",
No need to translate. It's API key

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"Dates","Dates",,
No need to translate.

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"ETAB",,"Key in FR",
No need to translate. It's API key

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"Kilometrice log","Historique barème kilométrique",,
Compteur kilométrique ?

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"LIEU",,"Key in FR",
No need to translate. It's API key

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"Login","Identifiant",,
No need to translate.

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"MATRICULE","MATRICULE","Key in FR",
No need to translate. It's API key

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"Messages","Messages",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"NOM",,"Key in FR",
No need to translate. It's API key

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"Plannings","Emplois du temps",,
Not sure about this

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"Salary change","Change de salaire",,
????

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> +"VILLE",,"Key in FR",
No need to translate. It's API key

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-maintenance/src/main/resources/i18n/messages_fr.csv
> +"Complete","Compléter",,
Terminer ?

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-maintenance/src/main/resources/i18n/messages_fr.csv
> +"Manufacturing order","Ordre de Fabrication",,
Ordre de fabrication

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-maintenance/src/main/resources/i18n/messages_fr.csv
> +"Name","Nom",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-maintenance/src/main/resources/i18n/messages_fr.csv
> +"Plan","Plan",,
Planifier? No need to translate (axelor-production)

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-maintenance/src/main/resources/i18n/messages_fr.csv
> +"Print","Imprimer",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-maintenance/src/main/resources/i18n/messages_fr.csv
> +"ProdProcess.machine","Machine",,
No need to translate (axelor-production)

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-maintenance/src/main/resources/i18n/messages_fr.csv
> +"Product","Produit",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-maintenance/src/main/resources/i18n/messages_fr.csv
> +"Production process","Gamme",,
No need to translate (axelor-production)

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-marketing/src/main/resources/i18n/messages_fr.csv
> +"Configuration","Configuration",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-marketing/src/main/resources/i18n/messages_fr.csv
> +"Email","Email",,
No need to translate

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-production/src/main/resources/i18n/messages_fr.csv
> +"Completed","Complété",,
Terminé ?

2022-04-29 18:07 UTC, gdu-axelor commented on axelor-production/src/main/resources/i18n/messages_fr.csv
> +"Configurator Prod Process filters","Filtres Gamme pour configurateur",,
Filtres configurateur de gamme

2022-05-02 08:08 UTC, ale-axelor commented
To be reopened when updated with correct information (see related issue).

2022-05-02 08:08 UTC, closed without merging