52070 fix of bank order line origin
axelor/axelor-open-suite pull request #8542
Opened 2022-07-18 14:25 UTC by rth-axelor

2022-07-18 16:36 UTC, gdu-axelor requested changes

2022-07-18 16:36 UTC, gdu-axelor commented on axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderLineOriginServiceImpl.java
> +        return invoiceTerm.getMoveLine().getOrigin() != null
Also need to check if is empty

2022-07-18 16:36 UTC, gdu-axelor commented on axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderLineOriginServiceImpl.java
>      } else if (model instanceof Reimbursement) {
I think a bankOrder can't be related to an Invoice anymore because now we use the InvoiceTerm, so please remove the related code and selection option

2022-07-19 12:49 UTC, jmi-axelor approved these changes

2022-07-19 12:49 UTC, merged