hide cancel btn when the purchase order is related to ventilated invo…
axelor/axelor-open-suite pull request #8752
Opened 2022-08-10 12:44 UTC by rth-axelor

…ices

2022-08-11 08:28 UTC, aol-axelor commented on axelor-purchase/src/main/resources/views/PurchaseOrder.xml
> +      if="__config__.app.isApp('supplychain') &amp;&amp; statusSelect == 3"/>
Please create new `action-group` in supplychain module calling `action-group-purchase-order-on-load-actions` and that new action

2022-08-11 08:28 UTC, aol-axelor commented on axelor-purchase/src/main/resources/views/PurchaseOrder.xml
> +
Same as before, please move to supplychain module

2022-08-11 08:28 UTC, aol-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderInvoiceServiceImpl.java
> +    return !relatedVentilatedInvoiceList.isEmpty();
Please use `count` instead of `fetch` and compare it to 0. Also, please use `bind` with variables names instead of `?` for better readability

2022-08-11 08:28 UTC, aol-axelor commented on changelogs/unreleased/fix-cancel-btn-purchase-order.yml
> +title: "Purchase Order : hide cancel btn when the purchase order is related to ventilated invoices"
Please write `button` instead of `btn`

2022-09-01 09:28 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderWorkflowServiceSupplychainImpl.java
>    @Transactional
Please fix the Transactionnal annotation, it could not rollback when an AxelorException is thrown here

2022-09-09 13:14 UTC, ale-axelor requested changes

2022-09-09 13:14 UTC, ale-axelor commented on axelor-purchase/src/main/java/com/axelor/apps/purchase/service/PurchaseOrderWorkflowServiceImpl.java
> +  @Transactional(rollbackOn = {AxelorException.class})
This was good before, this is a regression as it will not rollback on a NPE for example

2022-09-09 13:14 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderWorkflowServiceSupplychainImpl.java
> +  @Transactional(rollbackOn = {AxelorException.class})
same issue as above

2022-09-09 13:14 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderWorkflowServiceSupplychainImpl.java
>    @Transactional
Here it will not rollback on AxelorException, so please change it

2022-09-09 13:14 UTC, ale-axelor commented on axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/PurchaseOrderController.java
>    public void cancelReceipt(ActionRequest request, ActionResponse response) throws AxelorException {
please remove "throws AxelorException"

2022-10-05 09:54 UTC, closed without merging