54814 - FIXED ASSET / DEROGATORY DEPRECIATION : Incorrect derogatory …
axelor/axelor-open-suite pull request #9055
Opened 2022-09-28 13:58 UTC by alg-axelor

…depreciation plan

2022-09-28 15:12 UTC, jmi-axelor requested changes

2022-09-28 15:12 UTC, jmi-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineServiceImpl.java
> +    fixedAssetLineList.add(lastFixedAssetLineCopy);
Why don't you just set the depreciationDate in the fixedAssetLineList.get(lastIndex)?

2022-09-28 15:24 UTC, jmi-axelor approved these changes

2022-10-07 16:24 UTC, ale-axelor commented
see #9087

2022-10-07 16:24 UTC, closed without merging