55834 - MOVE/DAS2 : Moves are not correctly displayed considering DAS…
axelor/axelor-open-suite pull request #9168
Opened 2022-10-24 19:28 UTC by alg-axelor

…2 settings

2022-10-26 08:19 UTC, jmi-axelor approved these changes

2022-11-07 10:25 UTC, gdu-axelor requested changes

2022-11-07 10:25 UTC, gdu-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/PartnerAccountService.java
> +  @Transactional
We can't update all partner MoveLines like that. We can have serveral records. Period and JPA cache is not managed, we can't update some old move lines.

2022-11-07 10:25 UTC, gdu-axelor commented on axelor-base/src/main/resources/views/Partner.xml
> +      if="__config__.app.isApp('account')"/>
We can't run huge method on onSave event

2022-11-07 10:25 UTC, gdu-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/AccountService.java
> +  }
We can't update all account MoveLines like that. We can have serveral records. Period and JPA cache is not managed, we can't update some old move lines.

2022-11-07 10:25 UTC, gdu-axelor commented on axelor-account/src/main/resources/views/Account.xml
> +  <action-group name="action-account-group-onSave">
We can't run huge method on onSave event

2022-11-16 17:37 UTC, closed without merging