55668 - FEC IMPORT _ Technical error on move daybooking/accounting
axelor/axelor-open-suite pull request #9173
Opened 2022-10-25 21:04 UTC by alg-axelor

2022-10-26 15:55 UTC, jmi-axelor approved these changes

2022-10-28 09:30 UTC, ale-axelor requested changes

2022-10-28 09:30 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineToolServiceImpl.java
> +    if (move.getMoveLineList().size() == 0 || BigDecimal.ZERO.equals(moveLine.getCurrencyRate())) {
Please use compareTo or signum method instead of equals for BigDecimal

2022-10-28 09:30 UTC, ale-axelor commented on changelogs/unreleased/55668.yml
> +title: "FEC Import : fix invoice term generation"
Fix invoice term ? Invoice term does not exist on dev branch so I don't get the purpose of this change on 6.3 branch

2022-10-28 13:31 UTC, merged