57196 fix of taxline management in fixed asset cession
axelor/axelor-open-suite pull request #9314
Opened 2022-11-22 09:30 UTC by rth-axelor

2022-11-23 17:23 UTC, jmi-axelor requested changes

2022-11-23 17:23 UTC, jmi-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineMoveServiceImpl.java
> +          || (creditAccountTwo == null && creditAmountTwo.compareTo(BigDecimal.ZERO) > 0)
We'll get an NPE here, what are you trying to do?
Maybe: || creditAccountTwo == null || creditAmountTwo.compareTo(BigDecimal.ZERO) > 0 ??

2022-11-24 08:53 UTC, jmi-axelor approved these changes

2022-11-29 10:08 UTC, ale-axelor requested changes

2022-11-29 10:08 UTC, ale-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineMoveServiceImpl.java
> +          || (creditAccountTwo == null && creditAmountTwo.compareTo(BigDecimal.ZERO) > 0)
the condition seems wrong here, if creditAccountTwo is null we get a NPE.

2022-11-29 15:41 UTC, merged