60121 - Fix fill payment condition on move
axelor/axelor-open-suite pull request #9765
Opened 2023-02-01 17:20 UTC by paa-axelor

2023-02-02 14:03 UTC, jmi-axelor requested changes

2023-02-02 16:14 UTC, paa-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveTemplateService.java
> +        if (move.getDescription() != null && !move.getDescription().isEmpty()) {
Solved

2023-02-02 16:14 UTC, paa-axelor commented on axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineCreateServiceImpl.java
> +            move.getDescription() == null || move.getDescription().isEmpty()
Solved

2023-02-03 08:47 UTC, jmi-axelor approved these changes

2023-02-08 13:17 UTC, merged